language: node_js
node_js:
  - "8"

install: npm install

script: npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  verbose: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    recipients:
    - antonel.pazargic@gmail.com
    on_success: change
    on_failure: always
